### ISSUE TITLE
Can't install on Arch Linux (Makepkg was unable to build akonadi-ews)

### ISSUE THREAD

**Issue by alexchernokun** [KrissN/akonadi-ews#16] opened 2016-10-05 11:30 UTC
Scanning dependencies of target akonadi_ewsmta_resource
[ 94%] Building CXX object CMakeFiles/akonadi_ewsmta_resource.dir/ewsmtaresource.cpp.o
In file included from /tmp/yaourt-tmp-alex/aur-akonadi-ews/src/akonadi-ews-0.8.0/ewsmtaresource.cpp:20:0:
/tmp/yaourt-tmp-alex/aur-akonadi-ews/src/akonadi-ews-0.8.0/ewsmtaresource.h:41:10: warning:   by ‘virtual void EwsMtaResource::retrieveItems(const Akonadi::Collection&)’ [-Woverloaded-virtual]
     void retrieveItems(const Akonadi::Collection &collection) Q_DECL_OVERRIDE;
          ^~~~~~~~~~~~~
/tmp/yaourt-tmp-alex/aur-akonadi-ews/src/akonadi-ews-0.8.0/ewsmtaresource.cpp: In member function ‘bool EwsMtaResource::connectEws()’:
/tmp/yaourt-tmp-alex/aur-akonadi-ews/src/akonadi-ews-0.8.0/ewsmtaresource.cpp:58:32: error: ‘messageSent’ is not a member of ‘OrgKdeAkonadiEwsResourceInterface’
         connect(mEwsResource, &OrgKdeAkonadiEwsResourceInterface::messageSent, this, &EwsMtaResource::messageSent);
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/yaourt-tmp-alex/aur-akonadi-ews/src/akonadi-ews-0.8.0/ewsmtaresource.cpp: In member function ‘virtual void EwsMtaResource::sendItem(const Akonadi::Item&)’:
/tmp/yaourt-tmp-alex/aur-akonadi-ews/src/akonadi-ews-0.8.0/ewsmtaresource.cpp:85:19: error: ‘class OrgKdeAkonadiEwsResourceInterface’ has no member named ‘sendMessage’
     mEwsResource->sendMessage(item.remoteId(), mimeContent);
                   ^~~~~~~~~~~
make[2]: *** [CMakeFiles/akonadi_ewsmta_resource.dir/build.make:106: CMakeFiles/akonadi_ewsmta_resource.dir/ewsmtaresource.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:138: CMakeFiles/akonadi_ewsmta_resource.dir/all] Error 2
make: *** [Makefile:139: all] Error 2
==> ERROR: A failure occurred in package().
    Aborting...
==> ERROR: Makepkg was unable to build akonadi-ews.
==> Restart building akonadi-ews ? [y/N]
==> ------------------------------------
==>

**Comment by jo-mei** [comment] 2016-10-05 13:12
Hi,
I have the same problem with the akonadi-ews package on archlinux.
That's why I created the akonadi-ews-git package.
It gets the newest version from here and builds fine for me.

**Comment by alexchernokun** [comment] 2016-10-05 14:11
Hello,

Thank you for the info, will try it now and update you.

**Comment by alexchernokun** [comment] 2016-10-05 14:15
Yeah, that worked for me! Thanks a lot!

**Comment by jo-mei** [comment] 2016-10-08 07:37
Seems to be the same problem as #9 .
The patch from @hlavki fixes this as well.

**Comment by KrissN** [comment] 2016-10-24 16:59
Closing as duplicate of #9 then.

**Closed by KrissN** 2016-10-24 16:59 UTC
Labels: duplicate
