### ISSUE TITLE
KMail-17.04.3 doesn't allow to use/create EWSMTA "send-account" anymore

### ISSUE THREAD

**Issue by msva** [KrissN/akonadi-ews#45] opened 2017-08-09 14:12 UTC
Hi there!

I've found that after upgrade KMail to 17.04.3 it is not possible to add EWSMTA account (to be used for sending emails instead of SMTP) anymore.
It ignores the one created with `akonadiconsole`, and doesn't allow to create non-smtp outgoing account (the "Create" button directly opens dialog to create SMTP account).
Neither restarting `akonadiserver` helps (ewsmta account still doesn't show in outgoing accounts) 😿

**Comment by KrissN** [comment] 2017-08-09 15:10
This is a known regression in KDE PIM 17.04, which was done due to an unfortunate code cleanup that removed one functionality too many.

The regression has been fixed on master, but unfortunately it hasn't made it to the 17.04 maintenance branch. It will be working once 17.08 is released.

In the meantime please check bug #35 for workaround suggestions.

**Closed by KrissN** 2017-08-09 15:10 UTC
Labels: duplicate
